#:import hex kivy.utils.get_color_from_hex

# Base colors
#:set color_darker_black hex('#050505')
#:set color_off_black hex('#111111')
#:set color_gray_5 hex('#222222')
#:set color_gray_4 hex('#5A5A5A')
#:set color_gray_3 hex('#828282')
#:set color_gray_2 hex('#898989')
#:set color_gray_1 hex('#989898')
#:set color_off_white hex('#EEEEEE')
#:set color_red hex('FF0000')

#:set color_transparent (0, 0, 0, 0)